/*
 * Copyright 2026 zhengshuyun.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.zhengshuyun.lava.core.id;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

import static org.junit.jupiter.api.Assertions.*;

/**
 * @author Toint
 * @since 2026/1/6
 */
public class SeataSnowflakeTest {

    @Test
    void testNegativeWorkerId() {
        assertThrows(
                IllegalArgumentException.class,
                () -> {
                    new SeataSnowflake(-1L);
                },
                "should throw IllegalArgumentException when workerId is negative");
    }

    @Test
    void testTooLargeWorkerId() {
        assertThrows(
                IllegalArgumentException.class,
                () -> {
                    new SeataSnowflake(1024L);
                },
                "should throw IllegalArgumentException when workerId is bigger than 1023");
    }

    @Test
    void testNextId() {
        SeataSnowflake worker = new SeataSnowflake(null);
        long id1 = worker.nextId();
        long id2 = worker.nextId();
        assertEquals(1L, id2 - id1, "increment step should be 1");
    }

    @Test
    void testValidWorkerId() {
        // Test with a valid worker ID
        SeataSnowflake worker = new SeataSnowflake(1L);
        long id = worker.nextId();
        assertTrue(id > 0, "Generated ID should be positive");
    }

    @Test
    void testAutoGeneratedWorkerId() {
        // Test with auto-generated worker ID (null)
        SeataSnowflake worker = new SeataSnowflake(null);
        long id = worker.nextId();
        assertTrue(id > 0, "Generated ID should be positive");
    }

    @Test
    void testDifferentIds() {
        SeataSnowflake worker = new SeataSnowflake(null);
        long id1 = worker.nextId();
        long id2 = worker.nextId();
        assertNotEquals(id1, id2, "Generated IDs should be different");
    }

    @Test
    void testWorkerIdRange() {
        // Test worker IDs at boundaries
        SeataSnowflake worker1 = new SeataSnowflake(0L); // Minimum valid worker ID
        SeataSnowflake worker2 = new SeataSnowflake(1023L); // Maximum valid worker ID

        long id1 = worker1.nextId();
        long id2 = worker2.nextId();

        assertTrue(id1 > 0, "ID with minimum worker ID should be positive");
        assertTrue(id2 > 0, "ID with maximum worker ID should be positive");
    }

    /**
     * 校验 ID 位布局: 高 1 位为 0, 接着 10 位 workerId, 低 53 位为时间戳+序列号
     * <p>
     * 本类算法源自上游 Seata, 位布局是外部可见契约 (已落库的 ID 不可变), 任何重构都不得改动
     */
    @Test
    void testIdBitLayout() {
        int workerIdShift = 41 + 12;

        for (long workerId : new long[]{0L, 1L, 512L, 1022L, 1023L}) {
            long id = new SeataSnowflake(workerId).nextId();

            assertTrue(id > 0, "id must be positive (sign bit must stay 0)");
            assertEquals(workerId, id >>> workerIdShift,
                    () -> "workerId must occupy bits 53..62 for workerId=" + workerId);
        }
    }

    /**
     * 校验同一实例生成的 ID 严格连续递增 (Seata 改良算法的核心特性)
     */
    @Test
    void testIdsAreStrictlyIncrementing() {
        SeataSnowflake snowflake = new SeataSnowflake(1L);
        long previous = snowflake.nextId();

        for (int i = 0; i < 10_000; i++) {
            long current = snowflake.nextId();
            assertEquals(previous + 1, current, "ids must increase strictly by 1");
            previous = current;
        }
    }

    /**
     * 校验自动分配的 workerId 始终落在合法区间, 且不会因取不到 MAC 而构造失败
     */
    @Test
    void testAutoWorkerIdAlwaysValid() {
        int workerIdShift = 41 + 12;

        for (int i = 0; i < 50; i++) {
            long id = assertDoesNotThrow(() -> new SeataSnowflake().nextId(),
                    "auto workerId generation must never fail");
            long workerId = id >>> workerIdShift;
            assertTrue(workerId >= 0 && workerId <= 1023,
                    () -> "auto-generated workerId out of range: " + workerId);
        }
    }

    /**
     * 校验不同 workerId 的实例不会产生相同 ID (分布式场景的基本要求)
     */
    @Test
    void testDifferentWorkerIdsDoNotCollide() {
        SeataSnowflake a = new SeataSnowflake(1L);
        SeataSnowflake b = new SeataSnowflake(2L);

        Set<Long> ids = new HashSet<>();
        for (int i = 0; i < 1000; i++) {
            assertTrue(ids.add(a.nextId()), "duplicate id from worker 1");
            assertTrue(ids.add(b.nextId()), "duplicate id from worker 2");
        }
        assertEquals(2000, ids.size());
    }

    /**
     * 校验并发生成不产生重复 ID
     */
    @Test
    void testConcurrentGenerationHasNoDuplicates() throws Exception {
        SeataSnowflake snowflake = new SeataSnowflake(1L);
        int threads = 8;
        int perThread = 2000;

        List<Callable<List<Long>>> tasks = new ArrayList<>();
        for (int t = 0; t < threads; t++) {
            tasks.add(() -> {
                List<Long> ids = new ArrayList<>(perThread);
                for (int i = 0; i < perThread; i++) {
                    ids.add(snowflake.nextId());
                }
                return ids;
            });
        }

        ExecutorService pool = Executors.newFixedThreadPool(threads);
        try {
            Set<Long> all = new HashSet<>();
            for (Future<List<Long>> future : pool.invokeAll(tasks)) {
                all.addAll(future.get());
            }
            assertEquals(threads * perThread, all.size(), "concurrent generation produced duplicate ids");
        } finally {
            pool.shutdownNow();
        }
    }
}
